package view;

import control.FuncoesUteis;
import control.GerenciadorInterface;
import java.awt.Color;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;

/**
 *
 * @author Rafael
 */
public class DlgCadastrarCliente extends javax.swing.JDialog {

    /**
     * Creates new form DlgCadastrarCliente
     */
    private GerenciadorInterface gerenciador;

    public DlgCadastrarCliente(java.awt.Frame parent, boolean modal, GerenciadorInterface gerInter) {
        super(parent, modal);
        this.gerenciador = gerInter;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCadastroEndereco = new javax.swing.JFormattedTextField();
        txtCadastroNome = new javax.swing.JFormattedTextField();
        txtCadastroCPF = new javax.swing.JFormattedTextField();
        txtCadastroContato = new javax.swing.JFormattedTextField();
        txtCadastroCidade = new javax.swing.JFormattedTextField();
        txtCadastroBairro = new javax.swing.JFormattedTextField();
        txtCadastroNumero = new javax.swing.JFormattedTextField();
        btSalvarCadastroCliente = new javax.swing.JButton();
        btLimparCadastroCliente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Cliente"));

        txtCadastroEndereco.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtCadastroNome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtCadastroCPF.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPF", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        try {
            txtCadastroCPF.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtCadastroContato.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Contato", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        try {
            txtCadastroContato.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtCadastroCidade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cidade", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N
        txtCadastroCidade.setText("Linhares");

        txtCadastroBairro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bairro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        txtCadastroNumero.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "N°", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        btSalvarCadastroCliente.setBackground(new java.awt.Color(153, 255, 153));
        btSalvarCadastroCliente.setText("Salvar");
        btSalvarCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarCadastroClienteActionPerformed(evt);
            }
        });

        btLimparCadastroCliente.setBackground(new java.awt.Color(255, 153, 153));
        btLimparCadastroCliente.setText("Limpar");
        btLimparCadastroCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparCadastroClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCadastroNome)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCadastroCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCadastroCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCadastroBairro, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                            .addComponent(txtCadastroContato)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtCadastroEndereco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCadastroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimparCadastroCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvarCadastroCliente)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtCadastroNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastroCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadastroContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastroCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadastroBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCadastroEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCadastroNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvarCadastroCliente)
                    .addComponent(btLimparCadastroCliente))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarCadastroClienteActionPerformed
        String nome = txtCadastroNome.getText();
        String cpf = txtCadastroCPF.getText();
        String contato = txtCadastroContato.getText();
        String cidade = txtCadastroCidade.getText();
        String bairro = txtCadastroBairro.getText();
        String end = txtCadastroEndereco.getText();
        String numero = txtCadastroNumero.getText();

        String endereco = end + ", " + numero + " - " + bairro + ", " + cidade;

        if (validarCampos()) {

            // INSERIR NO BANCO
            try {

                // INSERIR
                int id = GerenciadorInterface.getInstance().getGerDom().inserirCliente(nome, cpf, contato, endereco);

                JOptionPane.showMessageDialog(this, "Cliente " + id + " inserido com sucesso.");

            } catch (HibernateException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }

    }//GEN-LAST:event_btSalvarCadastroClienteActionPerformed

    private void btLimparCadastroClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparCadastroClienteActionPerformed
        txtCadastroNome.setText("");
        txtCadastroCPF.setText("");
        txtCadastroContato.setText("");
        txtCadastroCidade.setText("Linhares");
        txtCadastroBairro.setText("");
        txtCadastroEndereco.setText("");
        txtCadastroNumero.setText("");
    }//GEN-LAST:event_btLimparCadastroClienteActionPerformed

    private boolean validarCampos() {
        String msgErro = "";

        txtCadastroNome.setForeground(Color.black);
        txtCadastroCPF.setForeground(Color.black);
        txtCadastroContato.setForeground(Color.black);
        txtCadastroCidade.setForeground(Color.black);
        txtCadastroBairro.setForeground(Color.black);
        txtCadastroEndereco.setForeground(Color.black);
        txtCadastroNumero.setForeground(Color.black);

        if (txtCadastroNome.getText().isEmpty()) {
            msgErro = msgErro + "Digite o nome.\n";
            txtCadastroNome.setForeground(Color.red);
        }

        if (txtCadastroCidade.getText().isEmpty()) {
            msgErro = msgErro + "Digite a cidade.\n";
            txtCadastroCidade.setForeground(Color.red);
        }

        if (txtCadastroBairro.getText().isEmpty()) {
            msgErro = msgErro + "Digite o bairro.\n";
            txtCadastroBairro.setForeground(Color.red);
        }

        if (txtCadastroEndereco.getText().isEmpty()) {
            msgErro = msgErro + "Digite o endereco.\n";
            txtCadastroEndereco.setForeground(Color.red);
        }

        if (FuncoesUteis.isCPF(txtCadastroCPF.getText()) == false) {
            msgErro = msgErro + "CPF inválido.\n";
            txtCadastroCPF.setForeground(Color.red);
        }

        try {
            int num = Integer.parseInt(txtCadastroContato.getText());
        } catch (NumberFormatException erro) {
            msgErro = msgErro + "Número inválido.\n";
            txtCadastroContato.setForeground(Color.red);
        } catch (Exception erro) {
            msgErro = msgErro + erro.getMessage() + "\n";
            txtCadastroContato.setForeground(Color.red);
        }

        // COLOCAR VALIDAÇÃO DOS OUTROS CAMPOS
        if (msgErro.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, msgErro, "ERRO Cliente", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btLimparCadastroCliente;
    private javax.swing.JButton btSalvarCadastroCliente;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField txtCadastroBairro;
    private javax.swing.JFormattedTextField txtCadastroCPF;
    private javax.swing.JFormattedTextField txtCadastroCidade;
    private javax.swing.JFormattedTextField txtCadastroContato;
    private javax.swing.JFormattedTextField txtCadastroEndereco;
    private javax.swing.JFormattedTextField txtCadastroNome;
    private javax.swing.JFormattedTextField txtCadastroNumero;
    // End of variables declaration//GEN-END:variables
}
