package view;

import model.Aparelho;
import model.Cliente;
import model.Nota;
import control.GerenciadorInterface;
import java.awt.Color;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import org.hibernate.HibernateException;

/**
 *
 * @author Rafael
 */
public class DlgCadastrarVenda extends javax.swing.JDialog {

    /**
     * Creates new form DlgCadastrarVenda
     */
    private GerenciadorInterface gerenciador;

    public DlgCadastrarVenda(java.awt.Frame parent, boolean modal, GerenciadorInterface gerenciador) {
        super(parent, modal);
        this.gerenciador = gerenciador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        panelValor = new javax.swing.JPanel();
        txtValor = new javax.swing.JFormattedTextField();
        panelParcelas = new javax.swing.JPanel();
        spnParcelas = new javax.swing.JSpinner();
        panelEntrada = new javax.swing.JPanel();
        txtDataEntrada = new javax.swing.JFormattedTextField();
        btSalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        txtValorParcelas = new javax.swing.JFormattedTextField();
        panelVencimento = new javax.swing.JPanel();
        txtVencimento = new javax.swing.JFormattedTextField();
        panelCliente = new javax.swing.JPanel();
        boxCliente = new javax.swing.JComboBox<>();
        panelAparelho = new javax.swing.JPanel();
        boxAparelho = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        panelPrincipal.setBorder(javax.swing.BorderFactory.createTitledBorder("Cadastro de Venda"));

        panelValor.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        try {
            txtValor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####.00")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtValor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorFocusLost(evt);
            }
        });

        javax.swing.GroupLayout panelValorLayout = new javax.swing.GroupLayout(panelValor);
        panelValor.setLayout(panelValorLayout);
        panelValorLayout.setHorizontalGroup(
            panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        panelValorLayout.setVerticalGroup(
            panelValorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelParcelas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parcelas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        spnParcelas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        spnParcelas.setModel(new javax.swing.SpinnerNumberModel(1, 1, 30, 1));

        javax.swing.GroupLayout panelParcelasLayout = new javax.swing.GroupLayout(panelParcelas);
        panelParcelas.setLayout(panelParcelasLayout);
        panelParcelasLayout.setHorizontalGroup(
            panelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnParcelas, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
        );
        panelParcelasLayout.setVerticalGroup(
            panelParcelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(spnParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelEntrada.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Entrada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        try {
            txtDataEntrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panelEntradaLayout = new javax.swing.GroupLayout(panelEntrada);
        panelEntrada.setLayout(panelEntradaLayout);
        panelEntradaLayout.setHorizontalGroup(
            panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDataEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        panelEntradaLayout.setVerticalGroup(
            panelEntradaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtDataEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        btSalvar.setBackground(new java.awt.Color(153, 255, 153));
        btSalvar.setText("Registar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        btLimpar.setBackground(new java.awt.Color(255, 153, 153));
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        txtValorParcelas.setEditable(false);
        txtValorParcelas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Valor das Parcelas", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        panelVencimento.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Vencimento dias:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        try {
            txtVencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout panelVencimentoLayout = new javax.swing.GroupLayout(panelVencimento);
        panelVencimento.setLayout(panelVencimentoLayout);
        panelVencimentoLayout.setHorizontalGroup(
            panelVencimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtVencimento, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
        );
        panelVencimentoLayout.setVerticalGroup(
            panelVencimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        panelCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        boxCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fulano", "Ciclano", "Beltrano" }));
        boxCliente.setSelectedIndex(-1);
        boxCliente.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                boxClienteComponentShown(evt);
            }
        });

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxCliente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addComponent(boxCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAparelho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aparelho", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12))); // NOI18N

        boxAparelho.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fulano", "Ciclano", "Beltrano" }));
        boxAparelho.setSelectedIndex(-1);
        boxAparelho.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                boxAparelhoComponentShown(evt);
            }
        });

        javax.swing.GroupLayout panelAparelhoLayout = new javax.swing.GroupLayout(panelAparelho);
        panelAparelho.setLayout(panelAparelhoLayout);
        panelAparelhoLayout.setHorizontalGroup(
            panelAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAparelhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(boxAparelho, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelAparelhoLayout.setVerticalGroup(
            panelAparelhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAparelhoLayout.createSequentialGroup()
                .addComponent(boxAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelPrincipalLayout = new javax.swing.GroupLayout(panelPrincipal);
        panelPrincipal.setLayout(panelPrincipalLayout);
        panelPrincipalLayout.setHorizontalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAparelho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btLimpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btSalvar))
                    .addGroup(panelPrincipalLayout.createSequentialGroup()
                        .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPrincipalLayout.createSequentialGroup()
                                .addComponent(panelValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(panelVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtValorParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 100, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelPrincipalLayout.setVerticalGroup(
            panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPrincipalLayout.createSequentialGroup()
                .addComponent(panelCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panelAparelho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(panelValor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelParcelas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(txtValorParcelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btSalvar)
                    .addComponent(btLimpar))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        boxCliente.setSelectedIndex(0);
        boxAparelho.setSelectedIndex(0);
        txtValor.setText("");
        spnParcelas.setValue(1);
        txtDataEntrada.setText("");
        txtVencimento.setText("");
        txtValorParcelas.setText("");
    }//GEN-LAST:event_btLimparActionPerformed
    private boolean validarCampos() {
        String msgErro = "";

        boxCliente.setForeground(Color.black);
        boxAparelho.setForeground(Color.black);
        txtValor.setForeground(Color.black);
        spnParcelas.setForeground(Color.black);
        txtDataEntrada.setForeground(Color.black);
        txtVencimento.setForeground(Color.black);
        txtValorParcelas.setForeground(Color.black);

        if (boxCliente.getSelectedIndex() == -1) {
            msgErro = msgErro + "Selecione um cliente.\n";
            boxCliente.setForeground(Color.red);
        }

        if (boxAparelho.getSelectedIndex() == -1) {
            msgErro = msgErro + "Selecione um aparelho.\n";
            boxAparelho.setForeground(Color.red);
        }

        Object spinnerValue = spnParcelas.getValue();

        if (spinnerValue == null) {
            msgErro = msgErro + "Selecione as parcelas.\n";
            ((JSpinner.DefaultEditor) spnParcelas.getEditor()).getTextField().setForeground(Color.red);
        } else {
            int valor = (int) spinnerValue;
            if (valor <= 0) {
                msgErro = msgErro + "O valor no Spinner deve ser maior que zero.\n";
                ((JSpinner.DefaultEditor) spnParcelas.getEditor()).getTextField().setForeground(Color.red);
            }
        }

        if (txtDataEntrada.getText().isEmpty()) {
            msgErro = msgErro + "Digite a cidade.\n";
            txtDataEntrada.setForeground(Color.red);
        }

        if (txtVencimento.getText().isEmpty()) {
            msgErro = msgErro + "Digite o bairro.\n";
            txtVencimento.setForeground(Color.red);
        }

        try {
            int num = Integer.parseInt(txtValor.getText());
        } catch (NumberFormatException erro) {
            msgErro = msgErro + "Número inválido.\n";
            txtValor.setForeground(Color.red);
        } catch (Exception erro) {
            msgErro = msgErro + erro.getMessage() + "\n";
            txtValor.setForeground(Color.red);
        }

        // COLOCAR VALIDAÇÃO DOS OUTROS CAMPOS
        if (msgErro.isEmpty()) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, msgErro, "ERRO Cliente", JOptionPane.ERROR_MESSAGE);
            return false;
        }
    }
    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        double totalVenda = (double) txtValor.getValue();
        int qtParcelas = (int) spnParcelas.getValue();
        Date dataEntrada = (Date) txtDataEntrada.getValue();
        Date dataVencimento = (Date) txtVencimento.getValue();
        double valorParcela = totalVenda / qtParcelas;
        txtValorParcelas.setValue(valorParcela);

        Calendar calendar = Calendar.getInstance();
        calendar.setTime(dataVencimento);

        Cliente novoCliente = (Cliente) boxCliente.getSelectedItem();
        Aparelho novoAparelho = (Aparelho) boxAparelho.getSelectedItem();

        List<Aparelho> aparelhos = new ArrayList<>();
        aparelhos.add(novoAparelho);

        List<Nota> notasPromissorias = new ArrayList<>();

        for (int i = 1; i <= qtParcelas; i++) {
            String numeroNota = i + "/" + qtParcelas;

            Date dataParcela = calendar.getTime();

            Nota novaNota = new Nota(valorParcela, numeroNota, dataParcela);

            notasPromissorias.add(novaNota);

            calendar.add(Calendar.MONTH, 1);
        }

        if (validarCampos()) {

            // INSERIR NO BANCO
            try {
                // INSERIR
                int id = GerenciadorInterface.getInstance().getGerDom().inserirVenda(novoCliente, notasPromissorias, aparelhos, dataEntrada, totalVenda, qtParcelas);

                JOptionPane.showMessageDialog(this, "Venda" + id + " inserido com sucesso.");

            } catch (HibernateException ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void txtValorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorFocusLost
        double totalVenda = (double) txtValor.getValue();
        int qtParcelas = (int) spnParcelas.getValue();
        double valorParcela = totalVenda / qtParcelas;
        txtValorParcelas.setValue(valorParcela);
    }//GEN-LAST:event_txtValorFocusLost

    private void boxClienteComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_boxClienteComponentShown
        gerenciador.carregarCombo(Cliente.class, boxCliente);
    }//GEN-LAST:event_boxClienteComponentShown

    private void boxAparelhoComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_boxAparelhoComponentShown
        gerenciador.carregarCombo(Aparelho.class, boxAparelho);
    }//GEN-LAST:event_boxAparelhoComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxAparelho;
    private javax.swing.JComboBox<String> boxCliente;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btSalvar;
    private javax.swing.JPanel panelAparelho;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelEntrada;
    private javax.swing.JPanel panelParcelas;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JPanel panelValor;
    private javax.swing.JPanel panelVencimento;
    private javax.swing.JSpinner spnParcelas;
    private javax.swing.JFormattedTextField txtDataEntrada;
    private javax.swing.JFormattedTextField txtValor;
    private javax.swing.JFormattedTextField txtValorParcelas;
    private javax.swing.JFormattedTextField txtVencimento;
    // End of variables declaration//GEN-END:variables
}
