package view;

import control.GerenciadorInterface;

/**
 *
 * @author Rafael
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal1
     */
    private GerenciadorInterface gerenciador;
    
    public FramePrincipal(GerenciadorInterface newGerenciador) {
        gerenciador = newGerenciador;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuConsultar = new javax.swing.JMenu();
        menuItemConsultaCliente = new javax.swing.JMenuItem();
        menuItemConsultarNota = new javax.swing.JMenuItem();
        menuCadastrar = new javax.swing.JMenu();
        menuItemNovoAparelho = new javax.swing.JMenuItem();
        menuItemNovoCliente = new javax.swing.JMenuItem();
        menuItemNovaVenda = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/paymentsysLogo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
        );

        menuConsultar.setText("Consultar");

        menuItemConsultaCliente.setText("Cliente");
        menuItemConsultaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultaClienteActionPerformed(evt);
            }
        });
        menuConsultar.add(menuItemConsultaCliente);

        menuItemConsultarNota.setText("Nota");
        menuItemConsultarNota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemConsultarNotaActionPerformed(evt);
            }
        });
        menuConsultar.add(menuItemConsultarNota);

        jMenuBar1.add(menuConsultar);

        menuCadastrar.setText("Cadastrar");

        menuItemNovoAparelho.setText("Novo Aparelho");
        menuItemNovoAparelho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoAparelhoActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemNovoAparelho);

        menuItemNovoCliente.setText("Novo Cliente");
        menuItemNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovoClienteActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemNovoCliente);

        menuItemNovaVenda.setText("Nova Venda");
        menuItemNovaVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemNovaVendaActionPerformed(evt);
            }
        });
        menuCadastrar.add(menuItemNovaVenda);

        jMenuBar1.add(menuCadastrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuItemNovaVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovaVendaActionPerformed
        gerenciador.abrirJanelaCadVenda();
    }//GEN-LAST:event_menuItemNovaVendaActionPerformed

    private void menuItemNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoClienteActionPerformed
        gerenciador.abrirJanelaCadCliente();
    }//GEN-LAST:event_menuItemNovoClienteActionPerformed

    private void menuItemNovoAparelhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemNovoAparelhoActionPerformed
        gerenciador.abrirJanelaCadAparelho();
    }//GEN-LAST:event_menuItemNovoAparelhoActionPerformed

    private void menuItemConsultarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultarNotaActionPerformed
        gerenciador.abrirJanelaConsultarNotas();
    }//GEN-LAST:event_menuItemConsultarNotaActionPerformed

    private void menuItemConsultaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemConsultaClienteActionPerformed
        gerenciador.abrirJanelaConsultarCliente();
    }//GEN-LAST:event_menuItemConsultaClienteActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JMenu menuCadastrar;
    private javax.swing.JMenu menuConsultar;
    private javax.swing.JMenuItem menuItemConsultaCliente;
    private javax.swing.JMenuItem menuItemConsultarNota;
    private javax.swing.JMenuItem menuItemNovaVenda;
    private javax.swing.JMenuItem menuItemNovoAparelho;
    private javax.swing.JMenuItem menuItemNovoCliente;
    // End of variables declaration//GEN-END:variables
}
